[FEAT] 유튜브 검색 화면 구현
Daylist-iOS/Daylist-iOS pull request #4
Opened 2022-06-13 13:35 UTC by yunkyung-Hwang

## 🌈 PR 요약
유튜브 검색 화면 구현
[공통] 로딩 화면 구현

## 📌 변경 사항
pod 'Kingfisher', '~> 7.0' 추가

## 📸 ScreenShot
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/61379671/173365723-faf7fd3e-c581-4b10-aa81-ac922e4729f8.gif)

#### Linked Issue
close #3

2022-06-13 18:20 UTC, hwangJi-dev requested changes
고생하셨어요~ 리뷰 한번만 확인해주시구 코멘트 달아주세용!!

2022-06-13 18:20 UTC, hwangJi-dev commented on Daylist/Daylist/Screen/Add/Cell/YoutubeSearchTVC.swift
> +        }
컴포넌트 변수들에 Label 붙여주면 좋을 것 같아요!

2022-06-13 18:20 UTC, hwangJi-dev commented on Daylist/Daylist/Screen/Add/ViewController/AddNC.swift
> +}
AddNC를 UINavigationController를 상속하는 클래스로 만들수도 있는데 
UIViewController를 상속하는 클래스로 만들어서 UINavigationController를 수동으로 넣어준 이유가 따로 있으신가요~?

2022-06-13 18:20 UTC, hwangJi-dev commented on Daylist/Daylist/Screen/Add/ViewController/YoutubeSearchVC.swift
> +class YoutubeSearchVC: BaseViewController {
더이상 상속되지 않는 클래스라면 앞에 final 붙이면 좋을 것 같아용!

2022-06-13 18:20 UTC, hwangJi-dev commented on Daylist/Daylist/Screen/Add/ViewController/YoutubeSearchVC.swift
> +    let naviBar = NavigationBar()
naviBar가 다른 클래스에서 직접 참조될 경우가 있어서 public으로 둔건가용~?

2022-06-15 09:13 UTC, yunkyung-Hwang commented on Daylist/Daylist/Screen/Add/ViewController/AddNC.swift
> +}
없어용!ㅋㅋㅋㅋ UINavigationController 상속으로 수정했습니다아

2022-06-15 09:14 UTC, yunkyung-Hwang commented on Daylist/Daylist/Screen/Add/ViewController/YoutubeSearchVC.swift
> +    let naviBar = NavigationBar()
private로 수정했습니다ㅏ~~~

2022-06-17 14:18 UTC, hwangJi-dev approved these changes
코드리뷰 반영하신거 확인했습니다 ~~ 고생하셨어요!!

2022-06-17 14:18 UTC, hwangJi-dev commented on Daylist/Daylist/Screen/Add/ViewController/AddNC.swift
> +        navigationController?.didMove(toParent: self)
훨씬 깔끔하네용!~!!

2022-06-17 14:27 UTC, merged